website/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('news', views.news_view, name='news_view')
]

website/programmer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'programmer'

urlpatterns = [
    path('home/', views.home_view, name='programmer_home'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home:home'), name='logout'),
    path('create_portfolio/', views.create_portfolio, name='create_portfolio'),
    path('view_portfolio/', views.view_portfolio, name='view_portfolio'),
    path('view_orders/', views.view_orders, name='view_orders'),
    path('news/', views.news_view, name='news_view'),
    path('taken_orders/', views.taken_orders, name='taken_orders'),
    path('contacts/', views.contacts, name='contacts'),
    path('portfolio/', views.edit_portfolio, name='edit_portfolio'),
    path('profile/', views.view_profile, name='view_profile'),
    path('take_order/', views.take_order, name='take_order'),
    path('delete_order/', views.delete_order, name='delete_order'),
    path('order/<int:order_id>/', views.view_order_detail, name='order_detail'),
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('programmer/', include('programmer.urls')),
    path('customer/', include('customer.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/home/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = "News"

website/programmer/models.py
from django.db import models
from django.conf import settings


class Portfolio(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE, default=None)
    image = models.ImageField(upload_to='images/')

    education = models.TextField()
    qualities = models.TextField()
    abilities = models.TextField()
    awards = models.TextField()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

website/home/forms.py
from django import forms
from .models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'slug', 'body', 'published']

website/programmer/forms.py
from django import forms
from .models import Portfolio


class PortfolioForm(forms.ModelForm):
    class Meta:
        model = Portfolio
        fields = ['image', 'education', 'qualities', 'abilities', 'awards']
    education = forms.CharField(required=False)
    awards = forms.CharField(required=False)

website/home/views.py
from django.shortcuts import render, redirect
from .models import News


def news_view(request):
    news = News.objects.filter().order_by('-published')
    if request.user.groups.filter(name='Программист').exists():
        return redirect(to='programmer:news_view')
    elif request.user.groups.filter(name='Заказчик').exists():
        return redirect(to='customer:news_view')
    else:
        return render(request, 'home/news_view.html', {'news': news})


# Create your views here.
def home_view(request):
    if request.user.groups.filter(name='Программист').exists():
        return redirect(to='programmer:programmer_home')
    elif request.user.groups.filter(name='Заказчик').exists():
        return redirect(to='customer:customer_home')
    else:
        return render(request, 'home/home.html')

website/programmer/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404, HttpResponseRedirect
from django.contrib.auth.decorators import user_passes_test
from django.utils import timezone
from customer.forms import CommentForm
from .forms import PortfolioForm
from .models import Portfolio
from customer.models import Order
from home.models import News



# Create your views here.
@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def home_view(request):
    try:
        portfolio = Portfolio.objects.get(user_id=request.user.id)
        has_portfolio = True
    except Portfolio.DoesNotExist:
        portfolio = None
        has_portfolio = False
    return render(request, 'programmer/home.html', {'has_portfolio': has_portfolio})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def create_portfolio(request):
    try:
        portfolio = Portfolio.objects.get(user_id=request.user.id)
        has_portfolio = True
    except Portfolio.DoesNotExist:
        portfolio = None
        has_portfolio = False
    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user_id = request.user.id
            form.save()
            # Дополнительный код обработки
            return render(request, 'programmer/portfolio_view.html', {'portfolio': portfolio})
    else:
        form = PortfolioForm()

    return render(request, 'programmer/portfolio_create.html', {'form': form, 'has_portfolio': has_portfolio})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def view_portfolio(request):
    try:
        portfolio = Portfolio.objects.get(user_id=request.user.id)
    except Portfolio.DoesNotExist:
        return redirect(to='programmer:create_portfolio')
    portfolio = Portfolio.objects.get(user_id=request.user.id)
    url = portfolio.image.url
    image_url = ''
    for x in range(19, len(url)):
        image_url += url[x]

    return render(request, 'programmer/portfolio_view.html', {'portfolio': portfolio, 'image_url': image_url})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def view_orders(request):
    orders = Order.objects.filter(programmer_id=None).order_by('-created')
    return render(request, 'programmer/view_orders.html', {'orders': orders})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def take_order(request):
    order_id = request.POST.get('order_id')
    order = get_object_or_404(Order, id=order_id)

    # Проверка, чтобы нельзя было взять заказ, если он уже взят другим программистом
    if order.programmer_id is not None:
        return HttpResponseForbidden("Этот заказ уже взят")

    # Установка programmer_id на ваш идентификатор пользователя
    order.programmer_id = request.user.id
    order.taken = timezone.now()
    order.save()
    orders = Order.objects.filter(programmer_id=request.user.id)
    return render(request, 'programmer/taken-orders.html', {'orders': orders})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def delete_order(request):
    order_id = request.POST.get('order_id')
    order = get_object_or_404(Order, id=order_id)

    # Проверка если заказ взят программистом
    if order.programmer_id:
        order.programmer_id = None
        order.taken = None
        order.save()

    orders = Order.objects.filter(programmer_id=request.user.id)
    return render(request, 'programmer/taken-orders.html', {'orders': orders})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def news_view(request):
    news = News.objects.filter().order_by('-published')
    return render(request, 'programmer/news_view.html', {'news': news})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def taken_orders(request):
    orders = Order.objects.filter(programmer_id=request.user.id)
    return render(request, 'programmer/taken-orders.html', {'orders': orders})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def contacts(request):
    return render(request, 'programmer/contacts.html')


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def edit_portfolio(request):
    portfolio = get_object_or_404(Portfolio, user_id=request.user.id)

    if request.method == 'POST':
        form = PortfolioForm(request.POST, request.FILES, instance=portfolio)
        if form.is_valid():
            form.save()
            return redirect(to='programmer:view_portfolio')  # Перенаправьте пользователя после успешного редактирования
    else:
        form = PortfolioForm(instance=portfolio)

    return render(request, 'programmer/portfolio_edit.html', {'form': form, 'portfolio': portfolio})


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def view_profile(request):
    return render(request, 'programmer/profile_view.html')


@user_passes_test(lambda u: u.groups.filter(name='Программист').exists())
def view_order_detail(request, order_id):
    # order_id = request.POST.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if 'done_button' in request.POST:
            order.is_done = True
            order.save()
        elif 'edit_button' in request.POST:
            order.is_done = False
            order.save()
        elif 'add_comm' in request.POST:
            if form.is_valid():
                form.instance.order = order
                form.instance.user = request.user
                form.save()
                form = CommentForm()
    else:
        form = CommentForm()
    comments = order.comments.all()
    return render(request, 'programmer/view_order_detail.html', {"order": order,
                                                                 "comments": comments,
                                                                 "form": form})

website/programmer/templates/programmer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'programmer/css/styles.css' %}">
    <link rel="icon" href="{% static 'home/favicon/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="logo-container">
            <a href="{% url 'programmer:programmer_home' %}">
                <div class="circle-center"></div>
                <svg class="logo" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                </svg>
            </a>
            <div class="logo-text-1"><a href="{% url 'programmer:programmer_home' %}">IT Park</a></div>
            <div class="logo-text-2"><a href="{% url 'programmer:programmer_home' %}">Juniors Gagauziya</a></div>
        </div>
        <menu>
            <a href="{% url 'programmer:news_view' %}">Новости</a>
            <a href="{% url 'programmer:view_portfolio' %}">Портфолио</a>
            <a href="{% url 'programmer:view_orders' %}">Заказы</a>
            <a href="{% url 'programmer:taken_orders' %}">Принятые заказы</a>
            <a href="{% url 'programmer:contacts' %}">Контакты</a>
        </menu>
        <div class="profile-icon">
            <a href="{% url 'programmer:view_profile' %}" class="profile-link">
                <div class="icon-head"></div>
            </a>
            <a href="{% url 'programmer:view_profile' %}" class="profile-link">
                <div class="icon-body"></div>
            </a>
        </div>
        <div class="auth-box">
            <a href="{% url 'programmer:logout' %}" class="logout-button">Выйти</a>
        </div>
    </header>

    {% block content %}
    {% endblock %}


    <section class="space">

    </section>

    <footer>
        <div class="footer-content">
            <p>&copy; <span id="current-year"></span> IT Park Gagauziya. Все права защищены.</p>
        </div>
    </footer>
</body>
<script src="{% static 'programmer/js/script.js' %}"></script>
<script src="{% static 'programmer/js/dd.js' %}"></script>
</html>

website/programmer/templates/programmer/contacts.html
{% extends "programmer/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h1 style="text-align: center;">Контакты</h1>

{% endblock %}

website/programmer/templates/programmer/home.html
{% extends "programmer/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="home_content">
  <h1>Доброго времени суток, программист {{ user.first_name }} {{ user.last_name }}</h1>
  {% if has_portfolio %}
    <h3>У вас уже есть Портфолио</h3>
  {% else %}
    <h3>Создайте Портфолио, чтобы показать свои навыки заказчикам</h3>
    <a href="{% url 'programmer:create_portfolio' %}">Создать Портфолио</a>
  {% endif %}
</div>


{% endblock %}

website/programmer/templates/programmer/news_view.html
{% extends "programmer/base.html" %}
{% block title %}News{% endblock %}
{% block content %}
    <section class="news">
        {% for x in news %}
        <div class="news-container">
            <h2>{{ x.title }}</h2>
            <h5>{{ x.published }}</h5>
            <h4>{{ x.body }}</h4>
        </div>
        {% endfor %}
    </section>
{% endblock %}

website/programmer/templates/programmer/portfolio_create.html
{% extends "programmer/base.html" %}
{% block title %}Portfolio{% endblock %}
{% block content %}
<div class="top-header=content">
 <div class="form_content">
  {% if not has_portfolio %}
      <h1>Создание Портфолио</h1>
      <p>Пожалуйста, заполните форму, чтобы создать Портфолио:</p>
      <form method="post" enctype="multipart/form-data">
      {{ form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Create"></p>
      </form>
  {% else %}
      <h1>У вас уже есть Портфолио</h1>
  {% endif %}
</div>
</div>

{% endblock %}

website/programmer/templates/programmer/portfolio_edit.html
{% extends "programmer/base.html" %}
{% block title %}Edit{% endblock %}
{% block content %}
<div class="top-header=content">
 <div class="form_content">
      <h1>Редактирование Портфолио</h1>
      <form method="post" enctype="multipart/form-data">
      {{ form.as_p }}
      {% csrf_token %}
      <p><input type="submit" value="Сохранить"></p>
      </form>

</div>
</div>

{% endblock %}

website/programmer/templates/programmer/portfolio_view.html
{% extends "programmer/base.html" %}
{% load static %}
{% block title %}Portfolio{% endblock %}
{% block content %}
<div class="portfolio">
    <div class="info-container">
         <h1>Привет, {{ user.first_name }} {{ user.last_name }}</h1>
        <div class="info-description">
            <div class="image-container">
                <img src="{{ portfolio.image.url }}" alt="photo">
            </div>
            <div class="description-container">
                 <h3>Образование:</h3>
                {{ portfolio.education }}
                <h3>Качества:</h3>
                {{ portfolio.qualities }}
                <h3>Навыки и умения:</h3>
                {{ portfolio.abilities }}
                <h3>Награды:</h3>
                {{ portfolio.awards }}
            </div>
        </div>
    </div>
</div>
<div class="buttons">
    <div class="edit">
        <a href="{% url 'programmer:edit_portfolio' %}">Редактировать Портфолио</a>
    </div>
</div>
{% endblock %}

website/programmer/templates/programmer/profile_view.html
{% extends "programmer/base.html" %}
{% load static %}
{% block title %}Portfolio{% endblock %}
{% block content %}
<div class="profile">
    <h3>Привет, {{ user.first_name }}</h3>
    {{ user }}

</div>


{% endblock %}

website/programmer/templates/programmer/taken-orders.html
{% extends "programmer/base.html" %}
{% block title %}Orders{% endblock %}
{% block content %}
    <section class="taken-orders">
        {% if orders %}
            <h1 style="text-align: center;">Здесь заказы за которые вы взялись!</h1>
            {% for order in orders %}
            <div class="order-container">
                <div class="inline-info">
                    <div class="order-title"><a href="{% url 'programmer:order_detail' order_id=order.id %}">{{ order.title }}</a></div>
                    <!-- {% url 'programmer:order_detail' order_id=order.id %} -->
                    <div class="taken">{{ order.taken }} {{ order.programmer.first_name }} принял Заказ</div>
                </div>
                <div class="order-line">
                    <div class="order-author"> {{ order.user.first_name }} {{ order.user.last_name }} </div>
                    <div class="last-update"> {{ order.updated }}</div>
                </div>

                <div class="order-body"> {{ order.full_subscription }} </div>
                {% if order.price %}
                    <div class="order-price">Цена: {{ order.price }} mdl</div>
                {% else %}
                    <div class="order-price">Цена: Договорная</div>
                {% endif %}
                <form method="post" action="{% url 'programmer:delete_order' %}">
                    {% csrf_token %}
                    <div class="buttons_">
                        <div class="delete">
                            <input type="hidden" name="order_id" value="{{ order.id }}">
                            <button type="submit">Удалить Заказ</button>
                        </div>
                    </div>
                </form>
            </div>
            {% endfor %}
        {% else %}
            <h1 style="text-align: center;">Вы не приняли ни одного заказа</h1>
        {% endif %}
    </section>
{% endblock %}

website/programmer/templates/programmer/view_order_detail.html
{% extends "programmer/base.html" %}
{% load static %}
{% block title %}Orders{% endblock %}
{% block content %}
<h1>{{ order.title }}</h1>
<h3>{{ order.full_subscription }}</h3>
{% if order.price %}
<h3>Цена: {{ order.price }} mdl</h3>
{% else %}
<h3>Цена: Договорная</h3>
{% endif %}
<h3>Заказчик: {{ order.user.first_name }} {{ order.user.last_name }}</h3>
<h3>Выполняет: {{ order.programmer.first_name }} {{ order.programmer.last_name }}</h3>
<h3>Создано: {{ order.created }}</h3>
<h3>Обновлено: {{ order.updated }}</h3>
{% if order.taken %}
<h3>Принят на выполнение: {{ order.taken }}</h3>
{% else %}
<h3>Заказ ещё никто не начал выполнять</h3>
{% endif %}
{% if order.is_done %}
<h2>Заказ выполнен</h2>
<form method="post">
    {% csrf_token %}
    <p><input type="submit" name="edit_button" value="Отменить выполнение"></p>
</form>
{% else %}
<form method="post">
    {% csrf_token %}
    <p><input type="submit" name="done_button" value="Подтвердить выполнение"></p>
</form>
{% endif %}

<h2>Comments</h2>
<ul>
    {% for comment in comments %}
    <li>{{ comment.text }} (by {{ comment.user.first_name }} {{ comment.user.last_name }})</li>
    {% endfor %}
</ul>

<!-- Форма для добавления нового комментария -->
<form method="post">
    {% csrf_token %}
    <h3>Добавить комментарий</h3>
    <div class="comment-text">
        {{ form.text }}
    </div>
    <p><input type="submit" name='add_comm' value="Добавить комментарий"></p>
</form>


{% endblock %}

website/programmer/templates/programmer/view_orders.html
{% extends "programmer/base.html" %}
{% load static %}
{% block title %}Orders{% endblock %}
{% block content %}
    {% if orders %}
    {% for order in orders %}

    <div class="order-container">

        <div class="order-title"><a href="{% url 'programmer:order_detail' order_id=order.id %}">{{ order.title }}</a></div>
        <!-- {% url 'programmer:order_detail' order_id=order.id %} -->
        <div class="order-line">
            <div class="order-author"> {{ order.user.first_name }} {{ order.user.last_name }} </div>
            <div class="last-update"> {{ order.updated }}</div>
        </div>
        <div class="order-body"> {{ order.full_subscription }} </div>
        {% if order.price %}
            <div class="order-price">Цена: {{ order.price }} mdl</div>
        {% else %}
            <div class="order-price">Цена: Договорная</div>
        {% endif %}
        <!--<h1>{{ order.id }}</h1> -->
        <form method="post" action="{% url 'programmer:take_order' %}">
            {% csrf_token %}
        <div class="buttons_">
            <div class="take">
                <input type="hidden" name="order_id" value="{{ order.id }}">
                <button type="submit">Принять заказ</button>
            </div>
        </div>
        </form>
    </div>
    {% endfor %}

    {% else %}
        <h1>Новых заказов нет!</h1>
    {% endif %}


{% endblock %}