website/customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'customer'

urlpatterns = [
    path('home/', views.home_view, name='customer_home'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home:home'), name='logout'),
    path('create_order/', views.create_order, name="create_order"),
    path('edit_order/', views.edit_order, name='edit_order'),
    path('delete_order/', views.delete_order, name='delete_order'),
    path('view_orders/', views.view_orders, name='view_orders'),
    path('view_programmers/', views.view_programmers, name='view_programmers'),
    path('news/', views.news_view, name='news_view'),
    path('404/', views.page_is_not_found, name='404'),
    path('order/<int:order_id>/', views.view_order_detail, name='order_detail'),

]

website/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('news', views.news_view, name='news_view')
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('programmer/', include('programmer.urls')),
    path('customer/', include('customer.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/customer/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    order_id = models.IntegerField(default=1)
    title = models.CharField(max_length=250)
    full_subscription = models.TextField()
    price = models.IntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='customer_orders')
    programmer = models.ForeignKey(User,
                                   on_delete=models.SET_NULL, null=True,
                                   blank=True, related_name='programmer_orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    taken = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)
    is_payed = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class Comment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.order.title}"

website/home/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = "News"

website/customer/forms.py
from django import forms
from .models import Order
from .models import Comment


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['title', "full_subscription", 'price']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 4}),
        }

website/home/forms.py
from django import forms
from .models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'slug', 'body', 'published']

website/customer/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from .forms import OrderForm, CommentForm
from .models import Order
from programmer.models import Portfolio
from home.models import News


# Create your views here.
@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def home_view(request):
    return render(request, 'customer/home.html')


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def create_order(request):
    try:
        order = Order.objects.filter(user_id=request.user.id).order_by('-created')[0]
        order_id = order.order_id
    except:
        order_id = 0
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            form.instance.user_id = request.user.id
            form.instance.order_id = order_id + 1
            form.save()
            orders = Order.objects.filter(user_id=request.user.id).order_by('-created')
            return render(request, 'customer/order_view.html', {'orders': orders})
    else:
        form = OrderForm()

    return render(request, 'customer/create_order.html', {'form': form})


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def edit_order(request):
    pass


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def delete_order(request):
    pass


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def view_orders(request):
    orders = Order.objects.filter(user_id=request.user.id).order_by('-created')
    return render(request, 'customer/order_view.html', {'orders': orders})


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def view_programmers(request):
    programmers = Portfolio.objects.all()
    return render(request, 'customer/view_programmers.html', {'programmers': programmers})


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def news_view(request):
    news = News.objects.filter().order_by('-published')
    return render(request, 'customer/news_view.html', {'news': news})


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def page_is_not_found(request):
    return render(request, 'customer/404.html')


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def handler404_(request, exception):
    return render(request, 'customer/404.html', status=404)


@user_passes_test(lambda u: u.groups.filter(name='Заказчик').exists())
def view_order_detail(request, order_id):
    # order_id = request.POST.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    if order.user != request.user:
        return render(request,
                      'customer/view_order_detail.html',
                      {"access_denied": True})

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.instance.order = order
            form.instance.user = request.user
            form.save()
            form = CommentForm()
    else:
        form = CommentForm()
    comments = order.comments.all()
    return render(request, 'customer/view_order_detail.html',
                  {"order": order,
                   "comments": comments,
                   "form": form})

website/home/views.py
from django.shortcuts import render, redirect
from .models import News


def news_view(request):
    news = News.objects.filter().order_by('-published')
    if request.user.groups.filter(name='Программист').exists():
        return redirect(to='programmer:news_view')
    elif request.user.groups.filter(name='Заказчик').exists():
        return redirect(to='customer:news_view')
    else:
        return render(request, 'home/news_view.html', {'news': news})


# Create your views here.
def home_view(request):
    if request.user.groups.filter(name='Программист').exists():
        return redirect(to='programmer:programmer_home')
    elif request.user.groups.filter(name='Заказчик').exists():
        return redirect(to='customer:customer_home')
    else:
        return render(request, 'home/home.html')

website/customer/templates/customer/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'customer/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'customer/css/access-denied.css' %}">
    <link rel="icon" href="{% static 'home/favicon/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="logo-container">
            <a href="{% url 'customer:customer_home' %}">
                <div class="circle-center"></div>
                <svg class="logo" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                </svg>
            </a>
            <div class="logo-text-1">IT Park</div>
            <div class="logo-text-2">Juniors Gagauziya</div>

        </div>
        <menu>
            <a href="{% url 'customer:news_view' %}">Новости</a>
            <a href="{% url 'customer:view_programmers' %}">Программисты</a>
            <a href="{% url 'customer:create_order' %}">Оформить заказ</a>
            <a href="{% url 'customer:view_orders' %}">Мои заказы</a>
            <a href="{% url 'customer:404' %}">Контакты</a>
        </menu>
        <div class="auth-box">
            <a href="{% url 'customer:logout' %}" class="logout-button">Выйти</a>
        </div>
    </header>

    {% block content %}
    {% endblock %}


    <section class="space">

    </section>

    <footer>
        <div class="footer-content">
            <p>&copy; <span id="current-year"></span> IT Park Gagauziya. Все права защищены.</p>
        </div>
    </footer>
</body>
<script src="{% static 'customer/js/script.js' %}"></script>
<script src="{% static 'customer/js/highlight.js' %}"></script>



</html>

website/customer/templates/customer/create_order.html
{% extends "customer/base.html" %}
{% block title %}Create{% endblock %}
{% block content %}
<div class="beautify-form-container">
    <div class='create-order'>
        <div class="text">
            <h1>Оформление Заказа</h1>
        </div>

        <div class="create-order-container">
    <form method="post">
        {% csrf_token %}

        <div class="form-group">
            <div class="label_">
                Название:
            </div>
<!--            {{ form.title.label_tag }} ////css style via label {} -->
            {{ form.title }}
        </div>

        <div class="form-group">
            <div class="label_">
                Полное описание:
            </div>
<!--            {{ form.full_subscription.label_tag }}-->
            {{ form.full_subscription }}
        </div>

        <div class="form-group">
            <div class="label_">
                Цена:
            </div>
<!--            {{ form.price.label_tag }}-->
            <p>
                {{ form.price }} mdl
            </p>


        </div>

        <p><input type="submit" value="Оформить Заказ"></p>
    </form>
</div>

    </div>
</div>

{% endblock %}

website/customer/templates/customer/home.html
{% extends "customer/base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div class="home_content">
  <h1>Доброго времени суток, заказчик {{ user.first_name }} {{ user.last_name }}</h1>
</div>
{% endblock %}

website/customer/templates/customer/news_view.html
{% extends "customer/base.html" %}
{% block title %}News{% endblock %}
{% block content %}
    <section class="news">
        {% for x in news %}
        <div class="news-container">
            <h2>{{ x.title }}</h2>
            <h5>{{ x.published }}</h5>
            <h4>{{ x.body }}</h4>
        </div>
        {% endfor %}
    </section>
{% endblock %}

website/customer/templates/customer/order_view.html
{% extends "customer/base.html" %}
{% block title %}Order{% endblock %}
{% block content %}
{% if orders %}
    {% for order in orders %}

    <div class="order-container">
        <div class="inline-info">
            <div class="order-title"><a href="{% url 'customer:order_detail' order_id=order.id %}">{{ order.title }}</a></div>
            {% if order.programmer %}
                <div class="taken">{{ order.taken }} выполняет {{ order.programmer.first_name }}</div>
            {% endif %}
        </div>
        <div class="order-line">
            <div class="last-update"> {{ order.updated }}</div>
        </div>
        <div class="order-body"> {{ order.full_subscription }} </div>
        {% if order.price %}
            <div class="order-price">Цена: {{ order.price }} mdl</div>
        {% else %}
            <div class="order-price">Цена: Договорная</div>
        {% endif %}
        <!--
        <div class="buttons">
            <div class="edit">
                <a href="#">Edit</a>
            </div>

            <div class="delete">
                <a href="#">Delete Order</a>
            </div>

        </div>
-->

    </div>
    {% endfor %}

    {% else %}
        <h1>Вы не оформили ни одного Заказа!</h1>
    {% endif %}


{% endblock %}

website/customer/templates/customer/view_order_detail.html
{% extends "customer/base.html" %}
{% load static %}
{% block title %}Orders{% endblock %}
{% block content %}


{% if access_denied %}
    <div id="access-denied-message" style="display: none;">
      <p>Доступ запрещен</p>
            <div class="cross-loading">
                <div class="customElement">
                    <div class="customBorder" id="close-button" onclick="closeAccessDenied()"></div>
                </div>
                <div class="cross"></div>
                <div class="cross2"></div>
            </div>

    </div>
    <div class="return-button">
        <a href="{% url 'customer:view_orders' %}">Вернуться к заказам</a>
    </div>

{% else %}
    <div class="order-container">
        <h1>{{ order.title }}</h1>
        <h3>{{ order.full_subscription }}</h3>
        {% if order.price %}
            <h3>Цена: {{ order.price }} mdl</h3>
        {% else %}
            <h3>Цена: Договорная</h3>
        {% endif %}
        <h3>Владелец: {{ order.user.first_name }} {{ order.user.last_name }}</h3>
        <h3>Создано: {{ order.created }}</h3>
        <h3>Изменено: {{ order.updated }}</h3>
        {% if order.taken %}
            <h3>{{ order.taken }} программистом {{ order.programmer.first_name }} {{ order.programmer.last_name }}</h3>
        {% else %}
            <h3>Заказ ещё никто не начал выполнять</h3>
        {% endif %}
    </div>
    <div class="order-container">

        <h2>Комментарии</h2>
        {% for comment in comments %}
            <div class="inline-comment">
                {% if comment.user.username == order.user.username %}
                    <div class="comment-author">Заказчик: </div>
                {% else %}
                    <div class="comment-author">{{ comment.user.first_name }}: </div>
                {% endif %}
                    <div class="comment-text">{{ comment.text }}</div>
            </div>
        {% endfor %}

    </div>

    <div class="new-comment-container">
        <!-- Форма для добавления нового комментария -->
        <form method="post">
            {% csrf_token %}
            <h3>Добавить комментарий</h3>
                {{ form.text }}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    </div>

{% endif %}



<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'customer/js/access-denied.js' %}"></script>

{% endblock %}

website/customer/templates/customer/view_programmers.html
{% extends "customer/base.html" %}
{% block title %}Programmers{% endblock %}
{% block content %}
{% for programmer in programmers %}
<div class="portfolio">
    <div class="info-container">
         <h1>{{ programmer.user.first_name }} {{ programmer.user.last_name }}</h1>
        <div class="info-description">
            <div class="image-container">
                <img src="{{ programmer.image.url }}" alt="photo">
            </div>
            <div class="description-container">
                <h3>Email:</h3>
                {{ programmer.user.email }}
                 <h3>Образование:</h3>
                {{ programmer.education }}
                <h3>Качества:</h3>
                {{ programmer.qualities }}
                <h3>Навыки и умения:</h3>
                {{ programmer.abilities }}
                <h3>Награды:</h3>
                {{ programmer.awards }}
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}