website/account/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    # path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register')
]

website/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home_view, name="home"),
    path('news', views.news_view, name='news_view')
]

website/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('programmer/', include('programmer.urls')),
    path('customer/', include('customer.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/home/models.py
from django.db import models
from django.utils import timezone


# Create your models here.
class News(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    body = models.TextField()
    published = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'News'
        verbose_name_plural = "News"

website/home/forms.py
from django import forms
from .models import News


class NewsForm(forms.ModelForm):
    class Meta:
        model = News
        fields = ['title', 'slug', 'body', 'published']

website/home/views.py
from django.shortcuts import render, redirect
from .models import News


def news_view(request):
    news = News.objects.filter().order_by('-published')
    if request.user.groups.filter(name='Программист').exists():
        return redirect(to='programmer:news_view')
    elif request.user.groups.filter(name='Заказчик').exists():
        return redirect(to='customer:news_view')
    else:
        return render(request, 'home/news_view.html', {'news': news})


# Create your views here.
def home_view(request):
    if request.user.groups.filter(name='Программист').exists():
        return redirect(to='programmer:programmer_home')
    elif request.user.groups.filter(name='Заказчик').exists():
        return redirect(to='customer:customer_home')
    else:
        return render(request, 'home/home.html')

website/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
    <link rel="icon" href="{% static 'home/favicon/favicon.ico' %}">
    <title>{% block title %}{% endblock %}</title>

</head>
<body>
    <header>
        <div class="logo-container">
            <a href="{% url 'home:home' %}">
                <div class="circle-center"></div>
                <svg class="logo" viewBox="0 0 100 100">
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                    <circle cx="50" cy="50" r="49" />
                </svg>
            </a>
            <div class="logo-text-1">IT Park</div>
            <div class="logo-text-2">Juniors Gagauziya</div>
        </div>
        <menu>
            <a href="{% url 'home:news_view' %}">Новости</a>
            <a href="#">Программисты</a>
            <a href="#">О нас</a>
            <a href="#">Контакты</a>
        </menu>
        <div class="auth-box">
            <div class="auth-buttons">
                    <a href="{% url 'account:login' %}" class="login-button">Войти</a>
                    <a href="{% url 'account:register' %}" class="register-button">Регистрация</a>
            </div>
        </div>
    </header>

    {% block content %}
    {% endblock %}



    <section class="space">

    </section>

    <footer>
        <div class="footer-content">
            <p>&copy; <span id="current-year"></span> IT Park Gagauziya. Все права защищены.</p>
        </div>
    </footer>

    <script src="{% static 'home/js/script.js' %}"></script>
</body>
</html>

website/home/templates/home/home.html
{% extends "home/base.html" %}
{% block title %}IT Park Gagauziya{% endblock %}
{% block content %}
    <section class="main-content">
        <h1>Добро пожаловать на наш сайт!</h1>
        <p>Здесь вы можете найти много интересной информации.</p>
        <!-- Добавьте свое содержание сюда -->
    </section>
{% endblock %}

website/home/templates/home/news_view.html
{% extends "home/base.html" %}
{% block title %}News{% endblock %}
{% block content %}
    <section class="news">
        {% for x in news %}
        <h2>{{ x.title }}</h2>
        <h5>{{ x.published }}</h5>
        <h4>{{ x.body }}</h4>
        {% endfor %}
    </section>
{% endblock %}